name: Deploy Application

on: 
  push:
    branches:
      -main
jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: windows-latest
    steps:
      -uses: actions/checkout@v2

      -name: Compile CSS and Javascript
       run: |
        echo npm install
        echo npm run prods